### ISSUE TITLE
Great Work! Issue FriendCodes

### ISSUE THREAD

**Issue by karimawi** [HypedDomi/BetterDiscordStuff#15]
### Discord Account

! 𝗞𝗮𝗿𝗶𝗺|ڪــرٻـــم#1111

### Describe the bug

Says could not be complied, restarted Discord, same issue.
![image](https://user-images.githubusercontent.com/69881381/180643294-0aabbbae-8203-4e6c-9a0d-64ba99de9968.png)

### How can I recreate this bug

idk, save the plugin and open discord?

**Comment by HypedDomi** [comment]
It works fine for me. Can you open the Console (`CTRL` + `Shift` + `I`) and send a screenshot of the Error
