### ISSUE TITLE
Midnightcord incompatible with ServerFolders plugin

### ISSUE THREAD

**Issue by FilterUnfiltered** [HypedDomi/BetterDiscordStuff#16]
### Discord Account

FilterUnfiltered#0001

### Describe the bug

ServerFolders has an option to show the number of servers in each folder, with a light blue version of the notification badge. This badge turns into the notification badge version when using this theme, meaning it always looks like I have notifications when I don't.

### How can I recreate this bug

1. Install ServerFolders plugin by DevilBro
2. Make sure "Display Badge for Amount of Servers in a Folder" option is turned on in the plugin settings
3. Install and enable Midnightcord
4. Create a server folder

**Comment by HypedDomi** [comment]
Should be fixed
