### ISSUE TITLE
All icons turned into ❓

### ISSUE THREAD

**Issue by karimawii** [HypedDomi/BetterDiscordStuff#17]
### Describe the bug

![image](https://user-images.githubusercontent.com/69881381/187293086-c4e6e189-d09d-49a6-9d51-5cadc6f9288c.png)

**Comment by HypedDomi** [comment]
Discord updated the attributes which broke the CSS Snippet i use for the Icons. I need to wait for a fix from the Snippet Author. But in the meantime i try to find a alternative

**Comment by HypedDomi** [comment]
I found a version that works. If there is a new issue regarding to the SettingsIcons, feel free to reopen the issue
