### ISSUE TITLE
[StatisticsCounter] Context Menu Crashes Discord

### ISSUE THREAD

**Issue by karimawii** [HypedDomi/BetterDiscordStuff#22]
### Discord Account

! 𝗞𝗮𝗿𝗶𝗺|ڪــرٻـــم#1111

### Describe the bug

When I right-click the counter, it crashes the client.

### How can I recreate this bug

1.Right-click the counter

it's one step lmao
(also thanks for maintaining this repo, I know how hard it can get sometimes, but you're bossing it so far, keep going 💪🏻 )

**Comment by HypedDomi** [comment]
I don't have any plugin with the name StatisticsCounter

**Comment by karimawii** [comment]
I'm sorry, I think I'm blind
