### ISSUE TITLE
[Feature Request][StatisticsCounter] Add a slider for font size

### ISSUE THREAD

**Issue by karimawii** [HypedDomi/BetterDiscordStuff#23]
On my laptop, the screen is smaller, so the counters appear stacked where the number is under the name of the counter, it looks kinda ugly and takes double the space, so I have to go in the code and edit the font sizes of the counters after every update, but I think implementing a slider would be useful, thanks.

**Comment by HypedDomi** [comment]
I don't have any plugin with the name StatisticsCounter

**Comment by karimawii** [comment]
Yeah, I'm definitely blind
