### ISSUE TITLE
(BetterInvites) plugin causes announcement channel to crash discord

### ISSUE THREAD

**Issue by onisonic** [HypedDomi/BetterDiscordStuff#26]
### Describe the bug

enable plugin and go in announcement channel
it can be fixed by reinstalling BetterDiscord throught "Repair" option
![изображение](https://github.com/HypedDomi/BetterDiscordStuff/assets/93402361/a22d23d7-214b-4641-9568-c3ee49bfb2cd)

### How can I recreate this bug

just enable plugin and go in announcement channel (no themes n' plugins other than this will crash discord, i tested it)
video proof: https://github.com/HypedDomi/BetterDiscordStuff/assets/93402361/afa32c88-917f-4418-8f66-d8a67c45b9ee

**Comment by HypedDomi** [comment]
BetterInvites is broken since a few Months. I haven’t had time yet to fix it due to my exams and my other projects. What you could try is this: https://github.com/HypedDomi/BetterDiscordStuff/issues/24#issuecomment-1561466322
I’ll close this issue since we have #24
