### ISSUE TITLE
BetterInvites Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [HypedDomi/BetterDiscordStuff#5]
### Discord Account

XxUnkn0wnxX#0002

### Describe the bug

As you can see the **BetterInvites** isn't working anymore since the recent update, a lot of plugins have broken
![Screen Shot 2022-02-04 at 8 21 05 pm](https://user-images.githubusercontent.com/2242880/152504243-450d3b99-1b85-44ac-aa20-2217d49d0b77.jpg)
![Screen Shot 2022-02-04 at 8 20 53 pm](https://user-images.githubusercontent.com/2242880/152504250-1c40de14-ff8f-4e62-83a3-4eeba8f3848e.jpg)

[discord.com-1643966471253.log](https://github.com/HypedDomi/BetterDiscordStuff/files/8001570/discord.com-1643966471253.log)
[debug.log](https://github.com/HypedDomi/BetterDiscordStuff/files/8001572/debug.log)

### How can i recreate this bug

just have the plugin running & try to look how an invite looks, nothing special is there all the extra banners & info about the invite are gone.

**Comment by HypedDomi** [comment]
i look into it

**Comment by HypedDomi** [comment]
Should be fixed with [bdd5281](https://github.com/HypedDomi/BetterDiscordStuff/commit/bdd5281b3f36090e5ce4bc3633f6852766c92151)
