### ISSUE TITLE
DownloadEmotes downloads to wrong directory

### ISSUE THREAD

**Issue by hiddeninthesand** [HypedDomi/BetterDiscordStuff#7]
### Describe the bug

On Linux, instead of downloading to `~/Downloads/Server/`, it downloads to `~/Downloads\Server/`, with the directory being named `Downloads\Server` instead of actually being two directories.

### How can i recreate this bug

1. Acquire a Linux instance with BetterDiscord and the plugin installed
2. Download emotes from a server
3. Check your home directory

**Comment by HypedDomi** [comment]
i dont have currently an linux instance, but i try to fix this c:

**Comment by hiddeninthesand** [comment]
The issue most likely has to do with Linux and Unix not using backslashes for directories, only forward slashes

**Comment by HypedDomi** [comment]
Should be fixed with [0157208](https://github.com/HypedDomi/BetterDiscordStuff/commit/01572081f0cf30230f129f7aa071401fdd94997f)

**Comment by hiddeninthesand** [comment]
It is, thank you!
